sudo: required
services:
  - docker

before_install:
  - docker build - t akhoulani/react-test -f ./client/Dockerfile../client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akhoulani/react-test npm run test

after_success:
  - docker build -t akhoulani/mulit-client ./client
  - dokcer build -t akhoulani/mulit-nginx ./nginx
  - docker build -t akhoulani/multi/server ./server
  - docker build -t akhoulani/multi/worker ./worker


